spring:
  application:
    name: itsrvsys
  datasource:
    dynamic:
      primary: mysql
      strict: false
      datasource:
        mssql:
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://10.2.81.1:1433;DatabaseName=PLOTECHNT;trustServerCertificate=true;encrypt=false;Timezone=GMT+8
          username: acmetech
          password: acmetech
          druid:
            initial-size: 5
            max-active: 20
            min-idle: 5
            max-wait: 60000
            min-evictable-idle-time-millis: 30000
            max-evictable-idle-time-millis: 30000
            time-between-eviction-runs-millis: 60000
        mysql:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://10.2.85.31:3306/jmreport?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: root
          password: P@ssw0rd! #acmetech #Local MySQL
          druid:
            initial-size: 5
            max-active: 20
            min-idle: 5
            max-wait: 60000
            min-evictable-idle-time-millis: 30000
            max-evictable-idle-time-millis: 30000
            time-between-eviction-runs-millis: 60000
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: plotechnt
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  servlet:
    multipart:
      max-file-size: 5MB

server:
  port: 8528
  tomcat:
    max-swallow-size: 50MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    aggressive-lazy-loading: true
    multiple-result-sets-enabled: true

minidao:
  base-package: org.jeecg.modules.jmreport.*,org.jeecg.modules.drag.*
  type: mysql

logging:
  level:
    org.jeecg.modules.jmreport: debug

jeecg:
  uploadType: minio #local/minio
  path:
    upload: ./jmreport/upload
  minio:
    minio_url: http://10.2.85.19:8529
    minio_name: admin
    minio_pass: 513andsm
    bucketName: base-bucket
  jmreport:
    firewall:
      lowCodeMode: prod #dev/prod/prodsf
      apiDsIpWhite:
        - 10.2.1.253
        - 127.0.0.1
        - 10.2.32.59
        - 10.2.85.30
      interval: 5000
    pageSize:
      - 1
      - 10
      - 20
      - 30

minio:
  endpoint: http://10.2.1.253:8529
  bucketName: base-bucket
  accessKey: admin # P8qVWlrkHPUAEG9nAbxB
  secretKey: 513andsm # TVibk4HRNpiFPUepvD9YffBJfxSX5jo79wU4c8Nb

com:
  plotech:
    token:
      key: plotech
      expire: 14400000

current:
  env: prod #dev/prod
dev:
  api: http://10.2.85.30:6666/ERP/MES/TServerMethods1/ISSAPIFun
prod:
  api: http://10.2.85.30:9001/ERP/MES/TServerMethods1/ISSAPIFun